<a href="https://colab.research.google.com/github/wisnalaa/Numerik/blob/main/Prak3_Metnum.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [12]:
import numpy as np

# Matriks yang akan difaktorisasi LU
A = np.array([[4, 3, 2],
              [2, 1, 3],
              [3, 3, 4]])

# Ukuran matriks
n = len(A)

# Inisialisasi matriks L dan U
L = np.zeros((n, n))
U = np.zeros((n, n))

# Faktorrisasi LU
for i in range(n):
    # Mengisi elemen diagonal utama matriks L dengan 1
    L[i, i] = 1

    # Menghitung elemen-elemen matriks U
    for j in range(i, n):
        U[i, j] = A[i, j] - sum(L[i, k] * U[k, j] for k in range(i))

    # Menghitung elemen-elemen matriks L
    for j in range(i + 1, n):
        L[j, i] = (A[j, i] - sum(L[j, k] * U[k, i] for k in range(i))) / U[i, i]

# Hasil faktorisasi
print("Matriks L: ")
print(L)
print("Matriks U: ")
print(U)

# Verifikasi hasil faktorisasi
print("Hasil perkalian matriks L dan U: ")
print(np.dot(L, U))

Matriks L: 
[[ 1.    0.    0.  ]
 [ 0.5   1.    0.  ]
 [ 0.75 -1.5   1.  ]]
Matriks U: 
[[ 4.   3.   2. ]
 [ 0.  -0.5  2. ]
 [ 0.   0.   5.5]]
Hasil perkalian matriks L dan U: 
[[4. 3. 2.]
 [2. 1. 3.]
 [3. 3. 4.]]


In [13]:
import numpy as np
from scipy.linalg import lu_factor, lu, lu_solve

# Matriks yang akan difaktorrisasi LU
A = np.array([[4, 3, 2],
              [2, 1, 3],
              [3, 3, 4]])

# vektor b
b = np.array([1, 2, 3])

# Faktorrisasi LU dan faktor faktorisasi
lu, piv = lu_factor(A)

# Solusi y dari Ly = b
y = lu_solve((lu, piv), b)

# Vektor Y
Y = np.array([4, 5, 6])

# Solusi x dari Ux = Y
x = lu_solve((lu, piv), Y)

# Hasil solusi
print("Solusi y: ")
print(y)
print("Solusi x: ")
print(x)

Solusi y: 
[-0.36363636  0.27272727  0.81818182]
Solusi x: 
[ 0.72727273 -0.54545455  1.36363636]


1. 4x + 3y + z = 24

    8x + 7y + 5z = 65

    4x + 6y + 10z = 60


In [14]:
import numpy as np
from scipy.linalg import lu_factor, lu, lu_solve

A11 = np.array([[4, 3, 1],
              [8, 7, 5],
              [4, 6, 10]])

b11 = np.array([24, 65, 60])

lu, piv = lu_factor(A11)

y11 = lu_solve((lu, piv), b11)

print("Solusi y11: ")
print(y11)

Solusi y11: 
[ nan  inf -inf]


/usr/local/lib/python3.12/dist-packages/scipy/_lib/_util.py:1233: LinAlgWarning: Diagonal number 3 is exactly zero. Singular matrix.
  return f(*arrays, *other_args, **kwargs)


In [15]:
import numpy as np
from scipy.linalg import lu_factor, lu, lu_solve

A1 = np.array([[4, 3, 1],
              [8, 7, 5],
              [4, 6, 10]])

b1 = np.array([24, 65, 60])

P1, L1, U1 = lu(A1)

print("Matriks L:\n", L1)
print("Matriks U:\n", U1)

lu_factorized = lu_factor(A1)

x1 = lu_solve(lu_factorized, b1)

print("\nHasil [x, y, z]: ")
print(x1)

Matriks L:
 [[ 1.   0.   0. ]
 [ 0.5  1.   0. ]
 [ 0.5 -0.2  1. ]]
Matriks U:
 [[8.  7.  5. ]
 [0.  2.5 7.5]
 [0.  0.  0. ]]

Hasil [x, y, z]: 
[ nan  inf -inf]


2.	2x + y + z = 1

    4x + 3y + 3z = 2

    8x + 7y + 9z = 3


In [16]:
import numpy as np
from scipy.linalg import lu_factor, lu, lu_solve

A22 = np.array([[2, 1, 1],
              [4, 3, 3],
              [8, 7, 9]])

b22 = np.array([1, 2, 3])

lu, piv = lu_factor(A22)

y22 = lu_solve((lu, piv), b11)

print("Solusi y22: ")
print(y22)

Solusi y22: 
[  3.5  60.5 -43.5]


In [17]:
import numpy as np
from scipy.linalg import lu_factor, lu, lu_solve

A2 = np.array([[2, 1, 1],
              [4, 3, 3],
              [8, 7, 9]])

b2 = np.array([1, 2, 3])

P2, L2, U2 = lu(A2)

print("Matriks L:\n", L2)
print("Matriks U:\n", U2)

lu_factorized = lu_factor(A2)

x2 = lu_solve(lu_factorized, b2)

print("\nHasil [x, y, z]: ")
print(x2)

Matriks L:
 [[1.         0.         0.        ]
 [0.25       1.         0.        ]
 [0.5        0.66666667 1.        ]]
Matriks U:
 [[ 8.          7.          9.        ]
 [ 0.         -0.75       -1.25      ]
 [ 0.          0.         -0.66666667]]

Hasil [x, y, z]: 
[ 0.5  0.5 -0.5]


---------------------------------------

In [18]:
import numpy as np
from scipy.linalg import lu_factor, lu_solve, lu

# Matriks A dan b
A21 = np.array([[2, 1, 1],
              [4, 3, 3],
              [8, 7, 9]])

b21 = np.array([1, 2, 3])

# 🔹 Dekomposisi LU secara eksplisit (untuk melihat L dan U)
P, L, U = lu(A21)

print("Matriks L:")
print(L)
print("\nMatriks U:")
print(U)
print("\nPerkalian P * L * U:")
print(P @ L @ U)  # cek hasilnya apakah kembali ke A11
print("\nApakah sama dengan A21?")
print(np.allclose(P @ L @ U, A21))  # True jika hasil sama (dalam batas toleransi float)

# 🔹 Dekomposisi untuk penyelesaian sistem persamaan
lu_factorized = lu_factor(A21)
y21 = lu_solve(lu_factorized, b21)

print("\nSolusi [x, y, z]:")
print(y21)


Matriks L:
[[1.         0.         0.        ]
 [0.25       1.         0.        ]
 [0.5        0.66666667 1.        ]]

Matriks U:
[[ 8.          7.          9.        ]
 [ 0.         -0.75       -1.25      ]
 [ 0.          0.         -0.66666667]]

Perkalian P * L * U:
[[2. 1. 1.]
 [4. 3. 3.]
 [8. 7. 9.]]

Apakah sama dengan A21?
True

Solusi [x, y, z]:
[ 0.5  0.5 -0.5]
