<a href="https://colab.research.google.com/github/wisnalaa/Numerik/blob/main/Prak3_IF2_Metnum.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
def dekomposisi_lu(A):

  n = A.shape[0]

  # Inisialisasi Matriks L (sebagai matriks identitas) dan U (salinan A)
  L = np.eye(n)
  U = A.copy()

  # Loop utama untuk eliminasi
  for k in range(n - 1): # k adalah kolom pivot
    # Cek untuk menghindari pembagian dengan nol
    if U[k, k] == 0:
      print("Error: Elemen diagonal zero pada posisi ({k}, {k}).")
      return None, None # Matriks mungkin singular atau perlu pivoting

    # Loop untuk setiap baris di bawah baris pivot
    for i in range(k + 1, n):

      # Hitung faktor pengali (multiplier)
      m = U[i, k] / U[k, k]

      # Simpan faktor pengali ke dalam Matriks L
      L[i, k] = m

      # Operasi Baris Elementer (membuat zero di bawah pivot di Matriks U)
      U[i, k:n] = U[i, k:n] - m * U[k, k:n]


  return L, U

In [2]:
def substitusi_maju(L, b):

  n = L.shape[0]
  y = np.zeros(n)

  # Loop melalui setiap baris
  for i in range(n):

    # Hitung sigma (jumlah perkalian elemen yang sudah diketahui)
    sigma = np.dot(L[i, 0:i], y[0:i])

    # Hitung y[i]
    y[i] = (b[i] - sigma) / L[i, i]

  return y

In [3]:
def substitusi_mundur(U, y):

  n = U.shape[0]
  x = np.zeros(n)

  # Loop mundur dari baris terakhir
  for i in range(n - 1, -1, -1):
    # Hitung sigma (jumlah perkalian elemen yang sudah diketahui)
    sigma = np.dot(U[i, i+1:n], x[i+1:n])

    # Hitung x[i]

    x[i] = (y[i] - sigma) / U[i, i]

  return x

In [4]:
# Definisi Matriks A dan Vektor b
A = np.array([
  [2.0, 1.0, 1.0],
  [4.0, -2.0, 3.0],
  [2.0, 4.0, -3.0]
])

b = np.array([4.0, 9.0, 1.0])

# --- Langkah 1: Dekomposisi ---
L, U = dekomposisi_lu(A)

if L is not None and U is not None:
  print("Matriks A:")
  print(A)

  print("\nMatriks L (Lower Triangular):")
  print(L)
  print("\nMatriks U (Upper Triangular):")
  print(U)

  # Verifikasi A = L @ U (seharusnya hasilnya mendekati A)
  A_rekonstruksi = L @ U
  print("\nVerifikasi L * U:")
  print(A_rekonstruksi)

  # --- Langkah 2: Substitusi Maju (Ly = b) ---
  y = substitusi_maju(L, b)
  print("\nVektor y dari Ly = b:")
  print(y)

  # --- Langkah 3: Substitusi Mundur (Ux = y) ---
  x = substitusi_mundur(U, y)
  print("\nVektor Solusi x dari Ux = y:")
  print(x)
  # Jawaban yang benar seharusnya mendekati x = [2.0, 1.0, -1.0]

Matriks A:
[[ 2.  1.  1.]
 [ 4. -2.  3.]
 [ 2.  4. -3.]]

Matriks L (Lower Triangular):
[[ 1.    0.    0.  ]
 [ 2.    1.    0.  ]
 [ 1.   -0.75  1.  ]]

Matriks U (Upper Triangular):
[[ 2.    1.    1.  ]
 [ 0.   -4.    1.  ]
 [ 0.    0.   -3.25]]

Verifikasi L * U:
[[ 2.  1.  1.]
 [ 4. -2.  3.]
 [ 2.  4. -3.]]

Vektor y dari Ly = b:
[ 4.    1.   -2.25]

Vektor Solusi x dari Ux = y:
[ 1.69230769 -0.07692308  0.69230769]
